### ISSUE TITLE
Hangs during "Downloading data"

### ISSUE THREAD

**Issue by yaroslavvb** [gedankenstuecke/one-button-tracker#4]
The "Install/connect" and "delete data" buttons seem to work as intended but "Downloading data" hangs. This same configuration worked for me a couple of days ago. Any suggestions how to troubleshoot?

Tried restarting bluetooth, deleting data, same result.
![Screen Shot 2021-05-15 at 3 11 50 PM](https://user-images.githubusercontent.com/23068/118379542-08a6cf80-b590-11eb-96a5-e0b6fdf062d5.png)

**Comment by yaroslavvb** [comment]
Worked after resetting Puck by following the instructions at http://forum.espruino.com/conversations/306194/

**Comment by gedankenstuecke** [comment]
I investigated this last weekend, as @esenabre had a similar issue (reported off-GH). I could not fully reproduce the issue myself but I know this happens in cases where there is no file of button pressed on the website. 

In @esenabre’s case a file was there and he could recover it through the [Espruino IDE](https://www.espruino.com/ide/). 

A general warning: The Pick has very limited memory unfortunately and if the file size becomes too large the files can get corrupted. Regularly offloading the files can prevent that.
